# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t1GxbwkzcYydt7BtlH8iSZ-qEye5dx2U
"""

import streamlit as st
import pandas as pd
import numpy as np
import random
import json
from typing import TypedDict, List
from faker import Faker
from openai import OpenAI
from datetime import date
from langgraph.graph import StateGraph, START, END

"""## UI CONFIGURATION"""

st.set_page_config(page_title="Wendy's FreshAi Strategy Board", layout="wide", page_icon="🍔")
st.title("🍔 Wendy's FreshAi Strategy Board")
st.markdown("### Synthesizing Market, Customer, and Competitive Intelligence")

"""## AGENT STATE DEFINITION"""

class MasterState(TypedDict):
    wendys_active: List[str]
    competitor_intel: dict  # Detailed metadata for traceability
    customer_insights: str
    market_trends: str
    raw_concepts: str
    structured_concepts: List[dict] # Synchronized data for Report + Scorecard
    final_report_text: str
    prioritization_table: pd.DataFrame

"""## AGENT NODES (CORE LOGIC)"""

def competitor_analyst_node(state: MasterState):
    """Calculates advanced Threat Scores: Saturation + Velocity + Recency Bias."""
    fake = Faker()
    today = date(2026, 1, 24)
    records = []
    for _ in range(500):
        records.append({
            "id": fake.uuid4()[:8],
            "brand": random.choice(["McDonald's", "Burger King", "Taco Bell"]),
            "mechanic": random.choice(["BOGO", "Gamified App Challenge", "Loyalty Multiplier"]),
            "obs_date": pd.to_datetime(fake.date_between(start_date='-60d', end_date=today))
        })
    df = pd.DataFrame(records)
    df['weight'] = np.exp(-0.05 * (pd.Timestamp(today) - df['obs_date']).dt.days)

    gaps = df[~df['mechanic'].isin(state["wendys_active"])]
    threats = []
    for mech, group in gaps.groupby('mechanic'):
        top_brand = group.groupby('brand')['weight'].sum().idxmax()
        score = round((group['weight'].sum() / 5), 1)
        # Inclusion of Traceability ID for "Signal Quality" score
        trace_id = group.sort_values('weight', ascending=False)['id'].iloc[0]
        threats.append(f"{mech} driven by {top_brand} (Threat: {score}/10) [Ref ID: {trace_id}]")

    return {"competitor_intel": {"summary": "\n".join(threats)}}

def customer_analyst_node(state: MasterState):
    """Analyzes behavioral signals for high-redemption segments."""
    insights = [
        "• Value-Oriented Mobile Users redeem app offers 1.002x more often.",
        "• Efficient Drive-Thru Diners redeem 1.004x more often via Drive-Thru."
    ]
    return {"customer_insights": "\n".join(insights)}

def trend_analyst_node(state: MasterState):
    """Detects emerging social themes and velocity."""
    trends = [
        "• Subscriptions (+113% velocity) trending on X associated with daily routines.",
        "• Gamification (+119% velocity) trending on Reddit associated with reward streaks."
    ]
    return {"market_trends": "\n".join(trends)}

def offer_designer_node(state: MasterState):
    """Fuses signals into creative concepts with defensive/pivot rules."""
    prompt = f"""
    You are Wendy's Lead Creative Strategist. Use these signals:
    GAPS: {state['competitor_intel']['summary']}
    INSIGHTS: {state['customer_insights']}
    TRENDS: {state['market_trends']}

    Task: Design 2 original Wendy's offers.
    Rule: One must be a 'Defensive' move and one must be a 'First-to-Market' creative pivot.
    Format: 'Name: [Name]. Why: [Evidence]. Strategy: [Defensive/Pivot].'
    """
    res = client.chat.completions.create(model="gemini-2.5-flash", messages=[{"role": "user", "content": prompt}])
    return {"raw_concepts": res.choices[0].message.content}

def brand_validator_node(state: MasterState):
    """Refines concepts into witty brand voice and synchronized JSON."""
    prompt = f"""
    Refine these concepts with Wendy's witty, fresh brand voice: {state['raw_concepts']}

    RETURN ONLY A JSON OBJECT with these keys:
    'intro': A 2-sentence witty overall summary.
    'offers': A list of objects with: 'name', 'rationale' (the witty text), 'type', 'feasibility' (1-10), 'impact' (1-10).
    """
    res = client.chat.completions.create(
        model="gemini-2.5-flash",
        response_format={"type": "json_object"},
        messages=[{"role": "user", "content": prompt}]
    )
    data = json.loads(res.choices[0].message.content)
    return {"structured_concepts": data["offers"], "final_report_text": data["intro"]}

def visualization_node(state: MasterState):
    """Builds the table scorecard using synchronized names."""
    table_data = [
        {"Concept": o["name"], "Feasibility": o["feasibility"], "Impact": o["impact"], "Type": o["type"]}
        for o in state["structured_concepts"]
    ]
    return {"prioritization_table": pd.DataFrame(table_data)}

"""## APP ASSEMBLY (SIDEBAR & RUNTIME)"""

"""## APP ASSEMBLY (SIDEBAR & RUNTIME)"""

st.sidebar.header("🔐 API Configuration")
try:
    openai_api_key = st.secrets["TIGER_API_KEY"]
    client = OpenAI(api_key=openai_api_key, base_url="https://api.ai-gateway.tigeranalytics.com")
except Exception:
    st.error("🔑 API Key not found. Please configure TIGER_API_KEY in your Streamlit Secrets.")
    st.stop()

# Ensure these widgets and the graph are defined outside the try block
st.sidebar.divider()
st.sidebar.header("🎯 Strategy Parameters")
wendys_current = st.sidebar.multiselect(
    "Wendy's Currently Active Promos",
    ["Biggie Bag", "4 for $4", "Breakfast 2 for $3", "BOGO Dave's Single"],
    default=["Biggie Bag", "4 for $4"]
)

# 3. COMPILE THE GRAPH (Ensuring this is reached during runtime)
builder = StateGraph(MasterState)
builder.add_node("comp", competitor_analyst_node)
builder.add_node("cust", customer_analyst_node)
builder.add_node("trend", trend_analyst_node)
builder.add_node("design", offer_designer_node)
builder.add_node("validate", brand_validator_node)
builder.add_node("viz", visualization_node)

builder.add_edge(START, "comp"); builder.add_edge(START, "cust"); builder.add_edge(START, "trend")
builder.add_edge("comp", "design"); builder.add_edge("cust", "design"); builder.add_edge("trend", "design")
builder.add_edge("design", "validate"); builder.add_edge("validate", "viz"); builder.add_edge("viz", END)
agent_app = builder.compile()

# 4. EXECUTION TRIGGER (Corrected indentation)
if st.sidebar.button("🚀 Generate Fresh Strategy"):
    with st.spinner("Executing multi-agent analysis..."):
        result = agent_app.invoke({"wendys_active": wendys_current})

        # Row 1: Individual Agent Insights
        st.markdown("## 🔎 Phase 1: Signal Intelligence")
        col1, col2, col3 = st.columns(3)
        with col1:
            st.info("**Competitor Threats**")
            st.write(result["competitor_intel"]["summary"])
        with col2:
            st.success("**Customer Insights**")
            st.write(result["customer_insights"])
        with col3:
            st.warning("**Market Trends**")
            st.write(result["market_trends"])

        st.divider()

        # Row 2: Final Strategic Report
        st.markdown("## ✨ Phase 2: Design & Brand Alignment")
        st.write(f"*{result['final_report_text']}*")

        for offer in result["structured_concepts"]:
            with st.expander(f"Offer: {offer['name']} ({offer['type']})", expanded=True):
                st.write(offer["rationale"])

        st.divider()

        # Row 3: Executive Scorecard
        st.markdown("## 📊 Phase 3: Executive Prioritization Scorecard")
        st.dataframe(
            result["prioritization_table"].style.background_gradient(cmap='YlOrRd', subset=['Feasibility', 'Impact']),
            use_container_width=True
        )
        st.balloons()





